services:
  sugar-frontend:
    build:
      context: ./Sugar_Frontend
    ports:
      - "3000:3000"
    depends_on:
      - sugar-backend

  sugar-backend:
    build:
      context: ./sugar-backend
    command: ./main
    ports:
      - "8080:8080"
    depends_on:
      - sugar-db
    environment:
      - DB_HOST=sugar-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=sugar-db
      - POSTGRES_PASSWORD=postgres

  sugar-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sugar-db
    restart: unless-stopped
